### ISSUE TITLE
Оформление

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#10]
- Линтер у тебя почему-то не видит ошибок в отсутствии запятых, но в стандартах airbnb указано, что нужно использовать висячие запятые: https://github.com/airbnb/javascript#commas--dangling
- Также нужно удалить комментарии
- Имена приватных переменных и методов в ts не обязательно начинать с нижнего подчеркивания, поскольку private и так указывает на приватность.

Это касается всего проекта.

**Comment by performanceArtist** [comment]
Сделал. А что не так с комментариями? И в ts после компиляции приватные методы ничем не отличаются от обычных - поэтому я их выделил дополнительно.

**Comment by viktoriya-ch** [comment]
> А что не так с комментариями?

Давай с другой стороны посмотрим - для чего ты их добавлял и почему возникла такая необходимость?
Твой код должен быть простым и понятным, если его требуется пояснять комментариями, то либо все не очевидно, либо твои методы слишком многим занимаются и не отвечают требованию Single Responsibility. Из названий классов, методов, функций должно быть и так ясно, зачем они нужны, и внутри не должно обнаруживаться ничего неожиданного и лишнего.
