### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#11]
Методы validate и setState выглядят довольно громоздкими, если тебе понадобилось пояснять их комментариями, значит, они трудно читаются. Использование в switch тернарников и if..else тоже читаемости не способствует, лучше бы это вынести.

**Comment by performanceArtist** [comment]
>Использование в switch тернарников

А что с ними не так? Не писать же функцию для каждого случая, когда нужно просто выбрать между двумя значениями.

**Comment by viktoriya-ch** [comment]
Ну после вынесения метода _validateValue явно стало лучше и validate разгрузился. Только вот имя для метода _validateValue лучше другое придумать, из его названия не понятно, какие именно значения он проверяет, учитывая то, что он предназначен только для 'value', 'firstValue' и 'secondValue'.

И еще, из стандартов, пункт 5: приватные методы размещаются после публичных https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/architecture.md

**Comment by viktoriya-ch** [comment]
Конфиг модели: из названий interval и horizontal непонятно, что они являются булевыми. 

 
![Снимок экрана в 2019-08-01 13-17-36](https://user-images.githubusercontent.com/38564412/62285784-0036e080-b45f-11e9-8270-7ed505476d8d.png)

**Comment by viktoriya-ch** [comment]
Здесь почти всё, осталось переименовать метод `_validateValue()`, потому что сейчас глядя на метод `validate()` не понятно, почему для первых трех `case` возвращается `validateValue`, а для остальных что-то другое, учитывая, что в этом методе они все у тебя называются `newValue`. В общем, нужны более подходящие имена, которые бы позволяли разграничивать разные значения между собой.

**Comment by performanceArtist** [comment]
Тут непонятно из-за того, что внутри функции под "value" подразумевается значение state, тогда как "value", "firstValue" и "secondValue" - значения слайдера. Переименовал метод как _validateSliderValue.

**Comment by viktoriya-ch** [comment]
В названии `validateSliderValue` всё еще мало конкретики, ведь весь твой плагин и называется slider, надо еще подумать, может быть range, или что-то еще более подходящее.

Функцию `getInitialState` нужно сделать методом класса (если она тут вообще нужна), а сам объект с дефолтным конфигом можно вынести в отдельный файл. И еще заметила, что у тебя в классе `Model` присутствует свойство с одноименным названием `_model`, его нужно переименовать, или и вовсе сразу в конструкторе объявить `this.state` (куда записать экспортированный дефолтный конфиг) и `this.meta `

**Comment by performanceArtist** [comment]
Пожалуй, можно разделить state и meta - смысла их вместе держать особо нет.
