### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#12]
Контроллер не должен содержать в себе обращения к DOM и обрабатывать браузерные события. Он только связывает view и model, подписываясь на них, и вызывая их публичные методы при необходимости. Все то, что у тебя сейчас содержится в контроллере, должно быть во вью. На данный момент кроме выполнения работы вью он ничем у тебя не занят.

**Comment by performanceArtist** [comment]
А зачем он тогда вообще, если он ничего делать не будет, кроме подписывания view на обновления модели? Тот же view это мог бы сделать парой строк.

**Comment by viktoriya-ch** [comment]
Он не будет подписывать вью, он сам подпишется на вью и модель, а те будут только генерировать события. И в зависимости от событий, контроллер будет вызывать какие-то методы вью и модели.

**Comment by performanceArtist** [comment]
А в чём мотивация? Зачем перенаправлять события? Предполагается, что там может быть дополнительная логика?

**Comment by viktoriya-ch** [comment]
Смысл в том, что нужно максимально отделить друг от друга модель и вью. У тебя сейчас вообще вью напрямую лезет в модель и изменяет стейт, такого быть не должно. Сейчас там содержатся рассчеты, которые должны быть только в модели, например:

`Math.abs(newValue - firstValue) < Math.abs(newValue - secondValue)` 

Зачем это знать виду?

Сейчас в задании написано, что вид должен быть пассивный, я не знаю, было ли это условие, когда ты делал задание, но при пассивном виде контроллер слушает вью и контроллер сам его изменяет, вью ничего не делает, только отправляет сообщения. Если же вид активный, то вью может подписываться на события модели и сам себя изменять. Но лезть в модель и менять ее ни при каком раскладе вью не должен, это задача контроллера.

Контроллер нужно подписать на вью, чтобы он получал оттуда необходимые данные. Менять модель из контроллера. Делать все рассчеты, связанные с моделью, в модели.

**Comment by performanceArtist** [comment]
Теперь контроллер слушает событие о новом значении и вызывает метод модели. По поводу `Math.abs...` - разве модели стоит уметь рефлексировать по поводу того, какое именно ей хотят установить значение? Зачем? Поставил эту логику в контроллер.

**Comment by viktoriya-ch** [comment]
> разве модели стоит уметь рефлексировать по поводу того, какое именно ей хотят установить значение?

Конечно, а кому же еще? Это ведь стейт модели. Модель получает запрос на установления значения, а там уже внутри себя думает - валидное оно или нет, стоит его менять или нет, или в данном случае - к какому именно значению относится запрос на изменение. Ни контроллер, ни вью оперировать такими значениями не должны.

**Comment by viktoriya-ch** [comment]
В контроллере по-прежнему присутствует что-то странное:

```
model.subscribe(view.update, 'update');
model.subscribe(view.render, 'render');
```
Вью и модель сейчас зависят друг от друга. Если ты что-то поменяешь в модели, тебе придется лезть во вью, и параллельно там тоже делать изменения. Например, у тебя поменяются названия свойств в модели и тебе придется менять метод view.update, поскольку в нем ты напрямую обращаешься к стейту. Писала выше, что контроллер:

> сам подпишется на вью и модель, а те будут только генерировать события. И в зависимости от событий, контроллер будет вызывать какие-то методы вью и модели.

То есть при наступлении события 'update' модель передает не просто имя события, но и данные, которые требуются вью для отрисовки. Контроллер слушает это событие, и когда оно происходит, вызывает свой метод, в котором вызывается метод вью с переданными параметрами, полученными от модели. Если что-то меняется во вью или модели, это должно затрагивать только контроллер.

**Comment by performanceArtist** [comment]
>Вью и модель сейчас зависят друг от друга.

View  в любом случае будет зависеть от модели, что в этом такого плохого? Если контроллер будет передавать данные модели view, а не сам view их будет брать, то что изменится? Также придётся менять имена - если конечно не переименовывать параметры в методах. В чём разница между `model.subscribe(() => view.update(this.model.getState()), 'update');` и просто `model.subscribe(view.update, 'update');`, внутри котого вызывается тот же `this.model.getState()`?

**Comment by viktoriya-ch** [comment]
Вопрос: Какую задачу выполняет твой контроллер?

>  В чём разница между model.subscribe(() => view.update(this.model.getState()), 'update'); и просто model.subscribe(view.update, 'update');

Здесь действительно нет никакой разницы. 

Я говорю о том, что надо в классе модели передать сразу `this.notify('update', ratio);` И тогда вью не будет необходимости лезть в модель, брать минимум, максимум и т.д. и делать рассчеты, которыми вьюха не должна заниматься. Точно так же вьюха не должна рассчитывать value модели, и потом делать `this.notify('newValue', value); `Она может отправить только ratio, а модель сама посчитает, какое значение установить. Все что нужно вьюхе для своих рассчетов, это соотношение длины слайдера и текущего положения бегунка. 

Таким образом, у тебя в контроллере будет что-то такое

```
model.subscribe(this.updateView, 'update');

updateView(ratio) {
  this.view.update(ratio)
}
```

и т. д.

Причем названия генерируемых событий тоже надо поменять, если модель изменила свои значения, то так событие и должно называться (changeValue, например). Если во вьюхе перетаскивается ползунок, то опять же, никакого отношения к newValue модели это событие пока что не имеет. Это просто событие вью, и оно может потребоваться теоретически другому компоненту в других целях.

**Comment by performanceArtist** [comment]
Многовато магии теперь у модели получается, конечно. Я задумывал её как максимально простой слой, который только получает объект, проводит валидацию и обновляет состояние, вдобавок играя роль публичного api - поэтому значения и высчитывались "снаружи". Сейчас с преобразованиями менее очевидно, хотя задание "обычных" значений работает также.

**Comment by performanceArtist** [comment]
>То есть при наступлении события 'update' модель передает не просто имя события, но и данные, которые требуются вью для отрисовки

Кстати, в контроллере пока осталось `model.subscribe(view.update, 'update');` - потому что у меня класс наблюдателя позволяет передавать данные. Сейчас модель оповещает так: 

```
this.notify('update', {
        value,
        ratio: (value - min) / (max - min),
      });
```

Или это нужно как-то в контроллер перенести? Получается, он по-прежнему ничего толком не делает.

**Comment by viktoriya-ch** [comment]
notify() в контроллер переносить не нужно, его должны вызывать компоненты, которые генерируют события. Вью генерирует свои события, модель свои. Контроллер их слушает.

Только не пойму, почему у тебя в модели до сих пор событие называется "render", модель ведь ничего не рендерит. 

Событие вью 'newValue' тоже нужно переименовать - вью ничего не знает о том, будет ли установлено новое значение, вью знает только, что произошел клик на шкале. Значит, событие должно называться примерно как-то так: "clickOnScale". По остальным названиям событий тоже посмотри. Они должны описывать, что произошло в компоненте, который их сгенерировал.

**Comment by viktoriya-ch** [comment]
**slider.ts**

![Снимок экрана в 2019-08-06 09-46-46](https://user-images.githubusercontent.com/38564412/62517026-27aaf600-b82f-11e9-9180-830be753161b.png)

Тут у тебя идет напрямую обращение к модели. У тебя части приложения могут обращаться к модели только через контроллер, так что в контроллер нужно добавить публичные методы. 

> Я задумывал её как максимально простой слой, который только получает объект, проводит валидацию и обновляет состояние, вдобавок играя роль публичного api - поэтому значения и высчитывались "снаружи".

Как раз-таки простота это про контроллер, а не модель. Так как контроллер самый зависимый класс (он зависит от вью и модели), он должен быть максимально простым. И по той же причине зависимости во вью и модели - плохо.

**Comment by performanceArtist** [comment]
>в контроллер нужно добавить публичные методы

А что в них должно быть? Нужно полностью туда переместить логику из модели? Или просто "обёртку" сделать для вызова того же setState?

**Comment by performanceArtist** [comment]
Как я понимаю, речь всё-таки об обёртках, т.к. код модели для неё специфичен.

**Comment by viktoriya-ch** [comment]
Да, всё верно
