### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#13]
- Почему функция createPanelInput не является методом класса? У нее даже из названия следует, что она относится к Panel.

- Далее, конструктор. По стандартам

> Конструктор класса должен быть максимально легковесным;
> 
> Например, если требуется провести поиск по DOM-дереву для задания значений полям класса, то нужно вынести этот функционал в отдельный метод. 

- Вынести обработчики событий

- Для того, чтобы превратить коллекцию в массив, используй оператор spread вместо метода call https://github.com/airbnb/javascript#arrays--from-iterable

**Comment by performanceArtist** [comment]
>Почему функция createPanelInput не является методом класса?

Я думал, как быть с функциями, которые независимы от this - вынести в отдельный модуль или повесить на сам класс(static). Пусть будет static - всё равно оно привязано к классу.
