### ISSUE TITLE
View

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#14]
Непосредственную обработку событий Handle стоит перенести в него (и заодно назвать его HandleView, а View переименовать в MainView), там генерить события для MainView. А MainView уже в свою очередь будет слушать HandleView, и генерить события для контроллера.

**Comment by viktoriya-ch** [comment]
Метод render слишком много делает. Если ты решил не выносить шкалу в отдельную вьюху, то хотя бы надо вынести ее в отдельный метод.

**Comment by performanceArtist** [comment]
Перенёс, но MainView пока что получается громоздкий - надо будет ещё подвигать.

**Comment by performanceArtist** [comment]
Думаю, так лучше. Теперь Main(view) занимается только управлением другими, а методы для изменения отображения содержатся в Slider и Handle. Можно даже не добавлять ползунки и сделать проверку на их наличие или опцию их отключения. Тогда останется "голый" Slider, менять значения которого можно только по клику шкалы.

**Comment by viktoriya-ch** [comment]
Да, так лучше стало. Только у тебя файлы ts должны называться точно так же, как и классы. Сейчас в файле `Main.ts` лежит класс  `View`. Было бы лучше назвать их MainView, HandleView, SliderView, чтобы было понятно, что это всё вьюхи.

**Comment by performanceArtist** [comment]
Но они и так лежат в папке Views, в которой кроме них ничего больше нет особо - думаю, суффикс не особо нужен.

**Comment by viktoriya-ch** [comment]
> Только у тебя файлы ts должны называться точно так же, как и классы. Сейчас в файле Main.ts лежит класс View.

**Comment by performanceArtist** [comment]
Имя поменял.
