### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#17]
По завершении правок проверить ошибки typescript, прогнать все линтером, починить тесты (а также дополнить их, сейчас для некоторых классов тесты отсутствуют)

**Comment by performanceArtist** [comment]
Сейчас ошибок компилятора нет, кроме случая с тестом модели, где намеренно передаётся неверный тип. По поводу тестов - насколько они должны быть детализированы? Каждый класс/компонент, каждый метод тестировать?

**Comment by viktoriya-ch** [comment]
Классы нужно тестировать все, демо-страницу только не обязательно. По поводу методов - тестируются только публичные методы, приватные тестировать не нужно.

**Comment by viktoriya-ch** [comment]
Обнови еще gh-pages во всех проектах
