### ISSUE TITLE
handler drag bug

### ISSUE THREAD

**Issue by alextsk** [performanceArtist/slider-plugin#2]
сейчас перетаскивание за точку работает только если курсор не выходит за пределы точки

**Comment by performanceArtist** [comment]
Вообще это не баг, а сделано сознательно, но пожалуй сейчас удобнее.

**Comment by alextsk** [comment]
пока без изменений, https://performanceartist.github.io/slider/ не обновлял?

**Comment by performanceArtist** [comment]
Сейчас обновил. Я туда в последнюю очередь переношу только.

**Comment by alextsk** [comment]
да, стало лучше. теперь при перетаскивании иногда залипает точка  - продолжает двигаться за мышью уже после mouseup

**Comment by performanceArtist** [comment]
Думаю, связано с тем, что текст с цифрами(значение, показатели шагов) может выделяться и что-то ломать. В любом случае, оно не слишком красиво. Сделал с css чисто пока, в современных браузерах должно работать.

**Comment by alextsk** [comment]
пока так же. возможно, это получается когда захватывается слайдер как объект, тут курсора не видно но это похоже на html drag 
![image (1)](https://user-images.githubusercontent.com/16453186/59904522-f5d00280-942d-11e9-9132-e9cce3608fe6.png)

**Comment by performanceArtist** [comment]
Сложно воспроизвести, это в каком браузере? Добавил заглушку для drag.

**Comment by alextsk** [comment]
обычный хром, сам обновляется

**Comment by performanceArtist** [comment]
Странно, ещё цифры почему-то внутри кругов - у меня их нет. Сейчас по-прежнему?

**Comment by alextsk** [comment]
цифры внутри - это как раз когда зажата мышь и перетаксивание идет, я их выровнял на круги чтобы их видно было
![image](https://user-images.githubusercontent.com/16453186/59906015-d33fe880-9431-11e9-8cf2-92346f5bd56c.jpg)
вот другой кусок 
тут я пытался схватить точку с 95

**Comment by alextsk** [comment]
я не думаю что это в браузере дело - я параллельно смотрю другие слайдеры и такой проблемы нет

**Comment by performanceArtist** [comment]
Если бы от бразуера не зависело, я бы мог легко воспроизвести, но я не могу - ни на Firefox, ни на Chrome. Поставил ещё один preventDefault в обработчике handleDrag, может поможет. Надо подумать ещё.

**Comment by alextsk** [comment]
сейчас уже не могу повторить - похоже заглушка помогла, просто изменения не сразу обновились в гитхабе

**Comment by performanceArtist** [comment]
Что-то там с Chrome и drag не так - до конца не понял, что. Можешь версию браузера сказать?

**Comment by alextsk** [comment]
Version 74.0.3729.131 (Official Build) (64-bit) - но зачем, все же заработало

**Comment by alextsk** [comment]
я на убунте если что

**Comment by performanceArtist** [comment]
Я не понял, почему заработало. То ли из-за того, что событии drag я поставил preventDefault, то ли из-за него же в mousedown.

**Comment by alextsk** [comment]
сложно сказать. я почему то не вижу коммитов с этими изменениями

**Comment by alextsk** [comment]
без drag работает, без  mousedown нет
но я думаю путь оба будут
