### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Frolikow** [performanceArtist/slider-plugin#4]
Сейчас у тебя слайдеры очень не очевидно себя ведут на демо-странице. 
1) Если слайдер для выбора интервала, например от 0 до 100, то почему в инпуте 100 выводит? логично сделать, чтобы было два инпута для каждого значения. 
2) Панель конфигураций. По какому принципу она работает? Почему она не подхватывает изначальные настройки? получается что при загрузке страницы, данные в панели не соответствуют действительности.
3) Так же в панели, если например сделать шаг 10, а потом удалить значение полностью, то слайдер продолжает работать с шагом 10
4) Надо бы подровнять значения шкалы
![image](https://user-images.githubusercontent.com/25764783/60562978-f9e01680-9d83-11e9-88d8-b884ffe64245.png)
100 как-будто вывалилось 

5) И я считаю, что надо нужно в целом переоформить страницу. Например расположить все слайдеры в столбик, для каждого слайдера задавать заголовок(  слайдер с шагом, с интервалом и т.п.). И для каждого слайдера рядом выводить панель конфигурации, чтоб было сразу видно какие настройки включены для слайдера. 

upd.
Также в панель нужно перенести инпут текущего значения, и если включен выбор интервала, то добавлять инпут для второго текущего значения.

**Comment by performanceArtist** [comment]
>Если слайдер для выбора интервала, например от 0 до 100, то почему в инпуте 100 выводит? 

Потому что это значение интервала: 100 - 0 = 100. Мне казалось очевидным. Не факт конечно, что так оно должно работать, но для одного инпута логично. Можно добавить и отдельные инпуты, пожалуй. 

>Панель конфигураций. По какому принципу она работает? Почему она не подхватывались изначальные настройки? получается что при загрузке страницы, данные в панели не соответствуют действительности.

В ней не было значений по умолчанию, а устанавливалось всё после события change - подхватывались сразу все значения. Можно и кнопку с submit поставить, если так более очевидно. В последнем коммите добавил автозаполнение настроек, чтобы было понятнее. 

>Так же в панели, если например сделать шаг 10, а потом удалить значение полностью, то слайдер продолжает работать с шагом 10

Пустые строки отбрасывались, чтобы ошибки не плодить. И естественно он продолжал работать с прежним значеним, так как пустая строка - значение неправильное. Теперь с автозаполнением думаю такое не нужно. Сейчас при пустом поле пишет ошибки, как и раньше для заполненных.

>перенести инпут текущего значения

Он уже рядом со слайдером есть. Или убрать оттуда? Оно по-разному работает. Инпут слайдера контролируется и молча синхронизируется со значениями, а значения с панели проверяются на правильность и не устанавливаются, пока сам пользователь правильно их не введёт. Хотя можно тоже было бы заполнять, но тогда было бы сложнее ошибки воспринимать - а так сразу видно, что ошибка про строку на месте числа и само это значение в инпуте.

По оформлению ещё подумаю, подправлю. Смысла большого делать много панелей не вижу, так как всё можно настроить на одной.

**Comment by performanceArtist** [comment]
>Надо бы подровнять значения шкалы

Тут надо подумать. Да, они несколько неровно смотрятся, но если двигать ползунок, то они будут чётко под ним находиться. Если "подровнять", тоже будет смотреться не очень.

**Comment by Frolikow** [comment]
> Потому что это значение интервала: 100 - 0 = 100. Мне казалось очевидным. Не факт конечно, что так оно должно работать, но для одного инпута логично. Можно добавить и отдельные инпуты, пожалуй.

первое что приходит на ум, где используется интервальный слайдер - это выбор диапазона цен. И вот тут точно надо два инпута, зачем пользователю, который хочет найти товар от 1000 до 10000, знать что разница значений 9к?))

> В ней не было значений по умолчанию, а устанавливалось всё после события change - подхватывались сразу все значения. Можно и кнопку с submit поставить, если так более очевидно. В последнем коммите добавил автозаполнение настроек, чтобы было понятнее.

Это надо не для того _чтобы было понятнее_, а по той причине что я смотрю на слайдер и на панель после загрузки страницы, и кто-то из врет. Это совсем не логичное поведение элементов, которые связаны друг с другом на прямую

> Пустые строки отбрасывались, чтобы ошибки не плодить. И естественно он продолжал работать с прежним значеним, так как пустая строка - значение неправильное. Теперь с автозаполнением думаю такое не нужно. Сейчас при пустом поле пишет ошибки, как и раньше для заполненных.

В этом случае нужно значит сделать ограничение для инпута, чтоб пустой строки там не могло оказаться в принципе. 

> По оформлению ещё подумаю, подправлю. Смысла большого делать много панелей не вижу, так как всё можно настроить на одной.

из задания:
![image](https://user-images.githubusercontent.com/25764783/61239029-27579780-a768-11e9-8f0d-c542dd4da0b1.png)
 И сюда же, я про инпуты говорил что их в панель запихать а не отдельно держать, это как минимум аккуратнее будет выглядеть.

> Тут надо подумать. Да, они несколько неровно смотрятся, но если двигать ползунок, то они будут чётко под ним находиться. Если "подровнять", тоже будет смотреться не очень.

Значит надо глобальнее "подправлять". Если я слева и справа сдвигаю ползунки на 1 шаг, то слайдер совсем не симметрично выглядит
![image](https://user-images.githubusercontent.com/25764783/61239344-db592280-a768-11e9-850a-7734748b66ab.png)
И нужно продумать как убрать кашу из цифр, если шаг 1 и включена шкала
![image](https://user-images.githubusercontent.com/25764783/61239400-faf04b00-a768-11e9-85a3-df9597f505c0.png)

**Comment by performanceArtist** [comment]
Добавил панели, вынес туда инпуты, сделал синхронизацию значений.

>Это надо не для того чтобы было понятнее, а по той причине что я смотрю на слайдер и на панель после загрузки страницы, и кто-то из врет. Это совсем не логичное поведение элементов, которые связаны друг с другом на прямую

Они напрямую как раз никак не связаны. Панель не является частью слайдера, она только и может, что взаимодействовать с ним через его интерфейс, как и всё остальное снаружи. Но неважно, сейчас значения панели должны соответствовать. 

>В этом случае нужно значит сделать ограничение для инпута, чтоб пустой строки там не могло оказаться в принципе.

Если ты про required, то оно будет работать только если сделать изменение значений через submit. Сейчас впрочем там пустого места не окажется, так как туда запишутся текущие значения вне зависимости от того, была ли успешной их установка или нет.

>Значит надо глобальнее "подправлять". Если я слева и справа сдвигаю ползунки на 1 шаг, то слайдер совсем не симметрично выглядит

С оформлением я ещё посмотрю. Кашу из цифр по идее никак не убрать - можно лишь ограничить их количество или сделать их очень мелкими, что тоже нечитаемо. Как буду css править, что-нибудь решу.

**Comment by performanceArtist** [comment]
Тесты сейчас кстати сломаны, я знаю. Проблема похоже с эмулированием вызова событий - после добавления классов и изменения принципа оповещения обработчики событий не вызываются. Оно обязательно? В принципе, тестирование модели тут самое важное - если что-то не так с событиями, будет и так очевидно. И саму панель стоит тестировать, если она лишь пользуется методами модели, для которых тесты есть?

**Comment by Frolikow** [comment]
> Они напрямую как раз никак не связаны.

Как раз таки связаны. Панель отображает текущее состояние слайдера, а слайдер выглядит именно так, как задано в панели конфигураций.

> Если ты про required, то оно будет работать только если сделать изменение значений через submit. 

Почему сразу   required, возможно нужно сделать через код логику для инпута. Но раз щас работает то ок. Потом будем смотреть код.

> С оформлением я ещё посмотрю. Кашу из цифр по идее никак не убрать - можно лишь ограничить их количество или сделать их очень мелкими, что тоже нечитаемо. Как буду css править, что-нибудь решу.

Мелкий шрифт, ты верно подметил, не вариант. Надо будет подумать как сделать, возможно задать какой-то минимум возможных значений под шкалой, и минимум этот будет зависеть от ширины/высоты слайдера.

> Тесты сейчас кстати сломаны, я знаю.

Не страшно что они сломаны, их можно будет под конец починить. А по покрытию, пока не смотрел код внимательно, но по-хорошему, надо чтоб все публичные методы были в тестах.

**Comment by Frolikow** [comment]
так же обнаружились еще баги
1)![image](https://user-images.githubusercontent.com/25764783/61431784-d8248900-a958-11e9-9b3e-c160aea7bf29.png)
значения 12 не может быть, и слайдер ставит 10 но иногда скачет до 12.
2)
![image](https://user-images.githubusercontent.com/25764783/61432491-d8be1f00-a95a-11e9-9f47-a2962770fa71.png)
С такими настройками возникли проблемы с изменением шага слайдера. При нажатии на стрелки внутри инпута, значение всегда приравнивается к 5 и вылезает ошибка. Ситуация: если у меня клавиатуры нету? как мне шаг изменить?
Надо сделать доступным изменение шага. По идее у шага только 2 ограничения должно быть: минимум - это 1, и максимум- это разница максимума и минимума.

**Comment by performanceArtist** [comment]
Да, этот вариант я забыл доработать. Можно обе проблемы решить, если подгонять max под шаг, а не просто выдавать ошибку, если разница max-min не делится. Нормальное же поведение?

>минимум - это 1, и максимум- это разница максимума и минимума

По идее больше нуля - дробные тоже могут быть, но да ладно.

**Comment by Frolikow** [comment]
> Да, этот вариант я забыл доработать. Можно обе проблемы решить, если подгонять max под шаг, а не просто выдавать ошибку, если разница max-min не делится. Нормальное же поведение?
> 
> > минимум - это 1, и максимум- это разница максимума и минимума
> 
> По идее больше нуля - дробные тоже могут быть, но да ладно.

А разница и не должна делиться. Например у тебя слайдер от 1 до 10. Шаг 4.
возможные значения будут 1,5,9,10. При чем надо будет учесть что слайдер будет шагать по шкале целые шаги, а от 9 до 10 будет расстояние 1/4 шага) Понял логику?  

и max под шаг подгонять не надо) получиться, что при изменении шага, будет меняться значение другого параметра. А это уже плохо

**Comment by performanceArtist** [comment]
Хорошо, что не надо - мне бы хотелось эту функцию чистой оставить. Просто в чате кто-то говорил что можно, кажется. Откатил обратно и нашёл косяк - условие неверное было, надо было нестрогое сравнение сделать. Если бы не это, работало бы правильно изначально.

**Comment by performanceArtist** [comment]
Поторопился - пофиксил, да не полностью и не то. Теперь должно работать.

**Comment by Frolikow** [comment]
Ага, сейчас нормально отрабатывает. Единственное что еще подфиксить надо, это если при таких настройках:
![image](https://user-images.githubusercontent.com/25764783/61587723-7b73d900-abb9-11e9-9067-da4c59b16341.png)
попытаться получить на слайдере 10, то надо курсор прям за слайдер уводить. Т.е. если слайдер будет прижат к правому краю окна браузера, то значение 10 уже не получить.

**Comment by performanceArtist** [comment]
Я там поменял регистр у некоторых файлов - всё работает?

**Comment by Frolikow** [comment]
> Я там поменял регистр у некоторых файлов - всё работает?

ругается, папки `panel `нету

**Comment by Frolikow** [comment]
по исправлениям ок, идем дальше
сейчас у тебя возможно такое что оба ползунка в одной точке могут находиться, это выглядит несколько не продумано, я предлагаю сделать ограничение для ползунков, чтоб каждый из них не мог к другому приблизится ближе чем на размер шага

**Comment by performanceArtist** [comment]
Да, я сам думал сделать - вполне логично, и реализовать просто. panel нет именно в файлах? Вообще не знаю, настолько ли  это хорошая идея - именовать здесь файлы с классом с pascal case - мне так привычнее, но могут ли от этого проблемы с тем же github-ом возникнуть?

**Comment by Frolikow** [comment]
Сейчас запулился, и не ругается. у Гита да, иногда бывают загоны по поводу регистра в именах файлов

**Comment by Frolikow** [comment]
> И нужно продумать как убрать кашу из цифр, если шаг 1 и включена шкала
> ![image](https://user-images.githubusercontent.com/25764783/61239400-faf04b00-a768-11e9-85a3-df9597f505c0.png)

вот этот вопрос еще не решен остался

**Comment by performanceArtist** [comment]
Забыл про то замечание. Сделал вычисление промежутка в зависимости от ширины и установку соответственного шага. 

Это конечно всё хорошо, но что по поводу кода? Подобные вещи править - пять минут, едва ли оно так важно для обучения.
