### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#6]
Если установлен размер шага 1, то после клика и перетаскивания бегунок дергается. Скорее всего, не учтено смещение курсора относительно бегунка. О том, как это исправить, можно почитать у Кантора (про shiftX, shiftY): https://learn.javascript.ru/drag-and-drop-objects

**Comment by viktoriya-ch** [comment]
![Peek 2019-07-30 17-00](https://user-images.githubusercontent.com/38564412/62136158-32740100-b2ec-11e9-8c99-09acca3389db.gif)

**Comment by performanceArtist** [comment]
>Скорее всего, не учтено смещение курсора относительно бегунка.

Нет, оно учтено: 

```
      const position = horizontal
        ? handleX + moveEvent.clientX - mouseX
        : handleY + moveEvent.clientY - mouseY;
```

Буду смотреть ещё, пока не совсем ясно, в чём там дело.

**Comment by performanceArtist** [comment]
Разобрался - дело в том, что у меня там есть ещё перемещение по клику. А mouseup как раз вызывает событие click, причём остановить это стандартными preventDefault/stopPropagation нельзя. Сделал установку булевой переменной и её проверку - не сильно красиво, но работает.

**Comment by performanceArtist** [comment]
Забыл ещё событие очистить - теперь должно работать.

**Comment by viktoriya-ch** [comment]
Все еще странно себя ведет: бегунок бежит быстрее мыши, останавливается например на значении 52, после отпускания мыши перескакивает на 59, и т.д.

![Peek 2019-08-01 09-29](https://user-images.githubusercontent.com/38564412/62270604-0d43d780-b43f-11e9-8854-066cd1ae6193.gif)

**Comment by performanceArtist** [comment]
У меня сейчас не перескакивает. Это в каком браузере? И я ещё не выкладывал на gh-pages.

**Comment by viktoriya-ch** [comment]
Я проверяю на локалке. Браузер Хром.

**Comment by performanceArtist** [comment]
Похоже проблема бьла в смещении относительно ширины ползунка - исправил в коммите с вынесением handleDrag в HandleView.

**Comment by viktoriya-ch** [comment]
Да, теперь правильно передвигается
