### ISSUE TITLE
JQuery

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#7]
В соответствии с заданием

> Плагин должен иметь удобное API для подключения его к элементам на странице и соответствовать best practices по созданию плагинов для jQuery.

Не обязательно использовать во всем проекте, но в конечном итоге твой плагин должен быть обернут в  jQuery. И почитай про best practices jQuery-плагинов, их не так много, но они упрощают подключение и настройку (удобно инициализировать, вызывать методы, задавать настройки через data-атрибуты).

Ко всему прочему, на данный момент у тебя слайдеры подключаются при помощи id элементов. А если нужно будет сделать два одинаковых слайдера на одной странице?

**Comment by performanceArtist** [comment]
>обернут в jQuery

Можно обернуть, но ничего это не даст - разве что можно data-атрибуты достать и дать функции плагина, но это можно и с обычным js сделать. Говорили будто, что можно и без JQuery на встрече - не совсем понял, как в итоге нужно. Как почитаю, посмотрю, можно ли как-нибудь добавить. 

>А если нужно будет сделать два одинаковых слайдера на одной странице?

id нужен только для панели и примеров - сделал как самый очевидный вариант привязки панели к слайдеру. Можно сделать ещё просто в js указание элемента, но тогда в миксине этого не задать. Создать несколько одинаковых слайдеров не проблема - просто вызывается init, к примеру: 
```
document.querySelectorAll('.slider').forEach(element => init(element, {interval: true}));
```

**Comment by viktoriya-ch** [comment]
> Можно обернуть, но ничего это не даст

Во-первых, это даст соответствие требованиям задания)

Дальше смотри, сейчас у тебя для того, чтобы инициализировать плагин, создается функция 

```
const createExample = (id: string, sliderOptions: Options = {}) => {
    const slider = init(document.getElementById(id), sliderOptions);
    new Panel(document.querySelector(`[data-slider=${id}]`), slider);
  };
```

И потом уже сама инициализация

```
createExample('example-1', {
    interval: true,
  });
```

С jQuery это всё бы писалось вот так коротко: 

`$('.example-1').slider();`

Чтобы вызвать какой-либо метод, было бы то же самое, только с параметром. 

`$('.example-1').slider('getState');`

Ну и все те же data-атрибуты, достаточно легкое добавление.

**Comment by viktoriya-ch** [comment]
> Говорили будто, что можно и без JQuery на встрече

Ты можешь написать весь плагин на чистом js, но потом обернуть его в jQuery с помощью небольшой jQuery функции, предназначенной для создания плагинов. Это и имелось ввиду.

**Comment by viktoriya-ch** [comment]
> id нужен только для панели и примеров

Использование id противоречит БЭМ и стандартам, это в любом случае надо заменить на классы. И заодно поменять имена example-1, example-2, тебе уже писали насчет этого в двух проектах.

**Comment by performanceArtist** [comment]
С функциями момент не ясен - а как мне их вызывать, собственно? Нужна какая-то привязка. Как использовать например тот же setState или subscribe, если селектор может выбрать несколько элементов? Где их взять изначально - каждый раз при вызове создавать для каждого элемента и хранить? Как-то странно это всё.

**Comment by viktoriya-ch** [comment]
Ну можно, например, в .data() всё хранить. Но если ты придумаешь какой-то более красивый вариант подключения jquery, то можешь реализовать по-другому.

**Comment by performanceArtist** [comment]
Обязательно прямо каждый метод с JQuery вызывать? Можно просто вернуть их при инициализации(хотя что делает JQuery тогда не особо ясно - получается, только атрибуты достаёт). Притом не нужно будет никаких передач строк-названий методов, вроде `$('.example-1').slider('getState');`, будут нормальные типы и подсказки, т.к. используются те же интерфейсы. Проверять, был ли `'.example-1'` уже создан как слайдер, тоже будет не надо.

**Comment by performanceArtist** [comment]
Можно ещё конечно возвращать не массив, а просто объект-интерфейс, если длина массива равна одному. Но я считаю лучше чётко знать, что будет на выходе и не думать о том, может ли там случайно быть слишком мало или слишком много элементов, а проверки и преобразования уже делать снаружи.

**Comment by viktoriya-ch** [comment]
Ты можешь просто проверять, какой тип аргумента был передан при инициализации, и в зависимости от результата либо вызывать метод, либо инициализировать плагин: https://habr.com/ru/post/158235/

Проверять, был ли создан слайдер, не нужно - а вдруг понадобится его заново инициализировать?

**Comment by performanceArtist** [comment]
>Ты можешь просто проверять, какой тип аргумента был передан при инициализации, и в зависимости от результата либо вызывать метод, либо инициализировать плагин: 

Как это сделать мне понятно. Но я считаю это плохой способ. И привязка к JQuery по-прежнему ничего не даёт, кроме дата-атрибутов, которые можно и без него взять. Да, сделал сейчас так, раз уж требование такое. Но на обычном js было бы куда чище. Сейчас надо будет ещё что-то с typescript мутить, так как непонятно, что может возвратить плагин. Интерфейс для публичных методов(SliderInterface) лежит зря и не используется - по строкам непонятно, что вообще можно вызвать. Можно конечно сделать составной тип для имён методов, но это будет очередной костыль. 

>Проверять, был ли создан слайдер, не нужно - а вдруг понадобится его заново инициализировать?

Нужно - если вызываем метод, нужно знать, был ли слайдер уже создан - иначе он каждый раз будет его заново инициализировать и перезапишет опции, которые могли быть переданы при создании или изменены через js, а не записаны в data-атрибуты.

**Comment by viktoriya-ch** [comment]
>  по строкам непонятно, что вообще можно вызвать

Посмотри для примера документацию каких-нибудь jQuery плагинов, обычно в них используются более конкретные публичные методы, чем просто обобщенные getState и setState. Ведь в теории плагин должен быть простым и наглядным в использовании. Например, документация карусели slick - множество методов и по названию каждого из них понятно, что он делает. Или те же Datepicker и Slider в jQuery UI.

А в ts в качестве типа ты можешь указать конкретные значения строки, чтобы было можно передать только их.

**Comment by performanceArtist** [comment]
Я сделал просто set и get, потому что настройки достаточно простые. Если сравнить с плагинами, то выходит, нужно для каждого отдельного метода сделать обёртку для вызова setState, чтобы вместо slider('setState', {interval: true}) было slider('interval', true)? Стоит ли? С объектом же проще и читается аналогично.

**Comment by performanceArtist** [comment]
И можно ещё тогда сделать для второго аргумента тип Options, чтобы были подсказки - раз есть только set и get.

**Comment by viktoriya-ch** [comment]
> И можно ещё тогда сделать для второго аргумента тип Options, чтобы были подсказки - раз есть только set и get.

Ок, тогда доделывай это и будем закрывать.

**Comment by performanceArtist** [comment]
Уже сделал, когда добавлял тесты.
