### ISSUE TITLE
Проверки, содержащие более одного условия

### ISSUE THREAD

**Issue by viktoriya-ch** [performanceArtist/slider-plugin#9]
По стандартам,

> Все проверки содержащие более одного условия должны быть вынесены

Например, вот здесь, в модели, лучше заменить на переменные

![Снимок экрана в 2019-07-31 16-45-53](https://user-images.githubusercontent.com/38564412/62217249-fc4d8480-b3b2-11e9-930b-d980238d96c9.png)

**Comment by performanceArtist** [comment]
В принципе, их кроме модели особо и не было. Есть `input.type === 'radio' || input.type === 'checkbox'`, но это и так очевидно. В модели есть ещё `newValue <= 0 || newValue > state.max - state.min` для step, но там и так ясно, что это просто проверка адекватности значения шага - выделять большого смысла нет.

**Comment by viktoriya-ch** [comment]
Смысл в том, чтобы другой разработчик при знакомстве с твоим кодом не читал все условие, а сразу прочитал по названию переменной / функции, что оно проверяет, не тратя на это лишнее время. Еще раз обрати внимание, что в стандартах написано "все проверки...", а не только те, которые тебе кажутся не очевидными)
